#!/bin/bash

set -eux

HOOKED_DIR=/home/ubuntu/hooked

# Check for Hooked configuration file

mkdir -p /home/ubuntu/hooked

if [ ! -f $HOOKED_DIR/projects.cfg ]; then
    cp $CHARM_DIR/templates/projects.cfg $HOOKED_DIR/projects.cfg
    chown ubuntu:ubuntu $HOOKED_DIR/projects.cfg
    chmod 755 $HOOKED_DIR/projects.cfg
fi

# Check for the upstart job to run hooked webservice
if [ ! -f /etc/init/webhooks.conf ]; then
    cp $CHARM_DIR/templates/webhooks.conf /etc/init/webhooks.conf
    chown root:root /etc/init/webhooks.conf
    chmod 755 /etc/init/webhooks.conf
fi

# Check for Build-Hook script

if [ ! -f $HOOKED_DIR/build-hook.py ]; then
    wget https://gist.githubusercontent.com/chuckbutler/dc8998499603f2789856/raw/3335f9ef115dcd493ce98a67a99719267e573fcc/build-hook.py -O /home/ubuntu/hooked/build-hook.py
    chmod 777 $HOOKED_DIR/build-hook.py
    chown ubuntu:ubuntu $HOOKED_DIR/build-hook.py
fi
